global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'perimeter-signature'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['perimeter-signature:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: perimeter-signature
      - source_labels: [__address__]
        target_label: service
        replacement: signature
    
  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: keycloak
      - source_labels: [__address__]
        target_label: service
        replacement: auth

  # Service discovery for dynamic components
  - job_name: 'perimeterai-services'
    dns_sd_configs:
      - names:
          - 'tasks.perimeter-signature'
          - 'tasks.keycloak'
        type: 'A'
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: service
        regex: 'tasks\.(.+)'
        replacement: '$1'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # - 'alertmanager:9093'

rule_files:
  - "rules/*.yml"
