version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:4000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - POSTGRES_URI=postgresql://postgres:5432/policy_studio
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: policy_studio
      POSTGRES_USER: policy_user
      POSTGRES_PASSWORD: policy_password
    volumes:
      - policy_studio_data:/var/lib/postgresql/data

volumes:
  policy_studio_data:
