global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'keycloak'
    metrics_path: '/auth/realms/master/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['keycloak:8443']
    basic_auth:
      username: 'prometheus'
      password: 'prometheus-password'

  - job_name: 'tenant-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['tenant-monitor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
