CREATE TABLE tenant (
    id VARCHAR(36) PRIMARY KEY,
    realm_id VARCHAR(36) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    admin_email VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    config JSONB,
    CONSTRAINT fk_realm FOREIGN KEY (realm_id) REFERENCES realm(id)
);
