---
- name: Setup Kubernetes Cluster
  hosts: kubernetes_nodes
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - kubectl
          - kubelet
          - kubeadm
        state: present
        update_cache: yes

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Initialize Kubernetes cluster
      command: kubeadm init
      when: inventory_hostname in groups['master']
